# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	1784859526	tb_session	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJTaXRlIE93bmVyIiwiaWF0IjoxNzg0ODE2MzI2LCJleHAiOjE3ODQ4NTk1MjZ9.WNqh6CekPqGWES7kLzE7wiZBJ5AyYoKsABdcFGpsCvU
